# vim: set ft=yaml ts=2 expandtab:
---

namespace: mafalb
name: logrotate
version: 0.0.1
readme: README.md

authors:
- Markus Falb <markus.falb@mafalb.at>

description: Ansible collection for logrotate

license:
- GPL-3.0-or-later

tags:
- logrotate

dependencies: {}

repository: https://github.com/mafalb/ansible-collection-logrotate
documentation: https://github.com/mafalb/ansible-collection-logrotate
homepage: https://github.com/mafalb/ansible-collection-logrotate
issues: https://github.com/mafalb/ansible-collection-logrotate/issues

...
