# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify
  hosts: all

  vars:
    logrotate_main_config: /etc/logrotate.conf
    logrotate_min_status_size: 175
    logrotate_status_file:
      Debian: /var/lib/logrotate/status
      RedHat: /var/lib/logrotate/logrotate.status

  tasks:

  - name: run logrotate # noqa 301
    check_mode: false
    command: /etc/cron.daily/logrotate

  - name: get status info
    stat:
      path: "{{ logrotate_status_file[ansible_os_family] }}"
    register: _logrotate_status

  - debug: var=_logrotate_status
    tags:
    - never
    - debug

  - name: assertions
    assert:
      that:
      - _logrotate_status.stat.size > {{ logrotate_min_status_size }}
      - logrotate_main_config|length > 0

  - name: xtmp is rotated
    when:
    - ansible_os_family == 'RedHat' and ansible_distribution_major_version < '8'
    command: grep -q '^/var/log/btmp' {{ logrotate_main_config }}

...
